version: '2.4'

services:

  app:
    # Build.
    image: krystalcode/matomo:fpm-alpine

    # Run.
    container_name: ${APP_ID}_app

    read_only: true

    restart: unless-stopped

    # Configure:
    depends_on:
      - mysql

    links:
      - mysql:mysql

    networks:
      - backend
      - frontend

    tmpfs:
      - /run:rw,noexec
      - /tmp:rw,noexec
      - /var/www/html/tmp:rw,noexec

    volumes:
      - app-html:/var/www/html
      - ./config:/var/www/html/config
      - ./misc-user:/var/www/html/misc/user

  nginx:
    # Build.
    image: nginx

    # Run.
    container_name: ${APP_ID}_nginx

    restart: unless-stopped

    # Configure.
    depends_on:
      - app

    links:
      - app:app

    environment:
      - VIRTUAL_HOST=${APP_VIRTUAL_HOST}
      - VIRTUAL_PORT=80
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=${APP_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${APP_LETSENCRYPT_EMAIL}

    networks:
      - frontend
      - proxy-tier

    volumes:
      - app-html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ${DOCKER_COMPOSE_VOLUMES_DIR}/${APP_VOLUMES_DIR}/misc-user:/var/www/html/misc/user

  mysql:
    # Build.
    image: percona:5.7

    # Run.
    command: --max_allowed_packet=64M --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    container_name: ${APP_ID}_mysql

    restart: unless-stopped

    # Configure.
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=${APP_MYSQL_ALLOW_EMPTY_PASSWORD}
      - MYSQL_USER=${APP_MYSQL_USER}
      - MYSQL_PASSWORD=${APP_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${APP_MYSQL_DATABASE}

    networks:
      - backend

    volumes:
      - ${DOCKER_COMPOSE_VOLUMES_DIR}/${APP_VOLUMES_DIR}/mysql:/var/lib/mysql

volumes:
  app-html:

networks:
  backend:
  frontend:

  proxy-tier:
    external:
      name: nginx-proxy
